export const FETCHING_CONTACTS = "FETCHING_CONTACTS";
export const FETCH_CONTACTS_SUCCESS = "FETCH_CONTACTS_SUCCESS";
export const FETCH_CONTACT_CHAT = "FETCH_CONTACT_CHAT";

export const FETCH_CONNECTION_REQUESTS = "FETCH_CONNECTION_REQUESTS";
export const ACCEPT_CONNECTION_REQUEST = "ACCEPT_CONNECTION_REQUEST";
export const DECLINE_CONNECTION_REQUEST = "DECLINE_CONNECTION_REQUEST";

export const SEND_CONNECTION_REQUEST = "SEND_CONNECTION_REQUEST";
export const FIND_USER_BY_USERNAME = "FIND_USER_BY_USERNAME";