export const X3DH_CONSTANTS_LOAD_SUCCESS = "X3DH_CONSTANTS_LOAD_SUCCESS";
export const X3DH_CONSTANTS_LOADING = "X3DH_CONSTANTS_LOADING";
export const GENERATE_IDENTITY_KEY = "GENERATE_IDENTITY_KEY";
export const GENERATE_PREKEY_BUNDLE = "GENERATE_PREKEY_BUNDLE";

export const FETCH_KEY_BUNDLE = "FETCH_KEY_BUNDLE";
export const PUBLISH_KEY_BUNDLE = "PUBLISH_KEY_BUNDLE";
export const PUBLISH_IDENTITY_KEY = "PUBLISH_IDENTITY_KEY";

export const SAVE_INITIAL_MESSAGE = "SAVE_INITIAL_MESSAGE";
export const SAVE_SHARED_KEY = "SAVE_SHARED_KEY";
export const INITIAL_MESSAGE_SUCCESSFULL = "INITIAL_MESSAGE_SUCCESSFULL";